#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v2
# autospec commit: e661f3a
#
Name     : jack2
Version  : 1.9.22
Release  : 14
URL      : https://github.com/jackaudio/jack2/archive/v1.9.22/jack2-1.9.22.tar.gz
Source0  : https://github.com/jackaudio/jack2/archive/v1.9.22/jack2-1.9.22.tar.gz
Summary  : the Jack Audio Connection Kit: a low-latency synchronous callback-based media server
Group    : Development/Tools
License  : GPL-2.0
Requires: jack2-bin = %{version}-%{release}
Requires: jack2-lib = %{version}-%{release}
Requires: jack2-license = %{version}-%{release}
Requires: jack2-man = %{version}-%{release}
BuildRequires : eigen-dev
BuildRequires : libsamplerate-dev
BuildRequires : opus-dev
BuildRequires : pkgconfig(alsa)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Makefile-quick-wrapper-for-waf.patch
Patch2: 0002-Workaround-old-waflib-trying-to-use-imp.patch

%description
-------------------------------
JACK2 on Windows
-------------------------------

%package bin
Summary: bin components for the jack2 package.
Group: Binaries
Requires: jack2-license = %{version}-%{release}

%description bin
bin components for the jack2 package.


%package dev
Summary: dev components for the jack2 package.
Group: Development
Requires: jack2-lib = %{version}-%{release}
Requires: jack2-bin = %{version}-%{release}
Provides: jack2-devel = %{version}-%{release}
Requires: jack2 = %{version}-%{release}

%description dev
dev components for the jack2 package.


%package lib
Summary: lib components for the jack2 package.
Group: Libraries
Requires: jack2-license = %{version}-%{release}

%description lib
lib components for the jack2 package.


%package license
Summary: license components for the jack2 package.
Group: Default

%description license
license components for the jack2 package.


%package man
Summary: man components for the jack2 package.
Group: Default

%description man
man components for the jack2 package.


%prep
%setup -q -n jack2-1.9.22
cd %{_builddir}/jack2-1.9.22
%patch -P 1 -p1
%patch -P 2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701982262
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701982262
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jack2
cp %{_builddir}/jack2-%{version}/COPYING %{buildroot}/usr/share/package-licenses/jack2/db95910cb27890d60e596e4c622fc3eeba6693fa || :
cp %{_builddir}/jack2-%{version}/android/NOTICE %{buildroot}/usr/share/package-licenses/jack2/56775a72fbc8b1416c51326851d83c2121a92c98 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jackd

%files dev
%defattr(-,root,root,-)
/usr/include/jack/control.h
/usr/include/jack/intclient.h
/usr/include/jack/jack.h
/usr/include/jack/jslist.h
/usr/include/jack/metadata.h
/usr/include/jack/midiport.h
/usr/include/jack/net.h
/usr/include/jack/ringbuffer.h
/usr/include/jack/session.h
/usr/include/jack/statistics.h
/usr/include/jack/systemdeps.h
/usr/include/jack/thread.h
/usr/include/jack/transport.h
/usr/include/jack/types.h
/usr/include/jack/uuid.h
/usr/include/jack/weakjack.h
/usr/include/jack/weakmacros.h
/usr/lib64/libjack.so
/usr/lib64/libjacknet.so
/usr/lib64/libjackserver.so
/usr/lib64/pkgconfig/jack.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/jack/audioadapter.so
/usr/lib64/jack/jack_alsa.so
/usr/lib64/jack/jack_alsarawmidi.so
/usr/lib64/jack/jack_dummy.so
/usr/lib64/jack/jack_loopback.so
/usr/lib64/jack/jack_net.so
/usr/lib64/jack/jack_netone.so
/usr/lib64/jack/jack_proxy.so
/usr/lib64/jack/netadapter.so
/usr/lib64/jack/netmanager.so
/usr/lib64/jack/profiler.so
/usr/lib64/libjack.so.0
/usr/lib64/libjack.so.0.1.0
/usr/lib64/libjacknet.so.0
/usr/lib64/libjacknet.so.0.1.0
/usr/lib64/libjackserver.so.0
/usr/lib64/libjackserver.so.0.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jack2/56775a72fbc8b1416c51326851d83c2121a92c98
/usr/share/package-licenses/jack2/db95910cb27890d60e596e4c622fc3eeba6693fa

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/jackd.1
